import type {Metadata} from 'next';
import Link from 'next/link';
import Image from 'next/image';
import MonitorPlanner from '@/components/MonitorPlanner';
export const metadata:Metadata={title:'Camera controls and the persistent anomaly warning',description:'An observed walkthrough of camera selection, a warning that persists on other feeds, and clearing the actual anomaly in SHIFT_MONITOR: 1998.',alternates:{canonical:'/guide/'}};
export default function Guide(){return <article className="page-shell max-w-4xl py-10"><p className="font-mono text-sm text-green-200">CONTROLS · OBSERVED BROWSER BUILD</p><h1 className="mt-4 text-3xl font-black leading-tight sm:text-5xl">Find the right camera before you purge</h1><p className="mt-5 text-lg leading-8 text-slate-300">If you switch cameras and still see “WARNING: ANOMALY DETECTED”, do not assume the new feed contains a second anomaly. In the build checked on 8 October 2026, that text can remain even when the visible entity is on another camera.</p>
<section className="mt-10 space-y-4 leading-8 text-slate-300"><h2 className="text-2xl font-bold text-white">The four camera buttons</h2><p>CAM 01 selects Main Hallway, CAM 02 selects Storage Room, CAM 03 selects Security Office, and CAM 04 selects Generator Bay. Read the label at the bottom left after switching to check which feed is active. These are the labels displayed in the running game, not four different difficulty tiers.</p><p>Use the camera buttons to examine the feeds. When you find the visible anomaly, keep that camera selected and press PURGE SIGNAL. The game’s supplied browser code checks whether the selected camera matches the anomaly’s camera. Pressing purge on another feed does not clear that anomaly.</p></section>
<section id="warning" className="mt-10 space-y-4 leading-8 text-slate-300"><h2 className="text-2xl font-bold text-white">Observed example: a warning on the wrong feed</h2><p>During an automated browser check, an anomaly appeared naturally in CAM 02, Storage Room. It was visible as a red shape, and the top-right status changed to the warning. After selecting another camera, the red shape was no longer visible, but the warning text remained.</p><figure><Image src="/images/observed-anomaly.png" width="1280" height="850" className="h-auto w-full rounded border border-green-300/20" alt="Red anomaly observed in the Storage Room before a successful purge"/><figcaption className="text-xs leading-6 text-slate-400">The affected Storage Room feed during the 8 October 2026 browser check. Carl Dev’s game, captured for this guide.</figcaption></figure><p>Returning to CAM 02 and pressing PURGE SIGNAL removed the shape. The status then became “SIGNAL: STABLE”. This is a useful distinction when learning the controls: a persistent warning means you should inspect the feeds, not repeatedly purge whichever camera is currently selected.</p><p>The checked code also explains the behavior. Switching away hides the entity; it does not reset the warning while an anomaly exists elsewhere. A successful purge clears the anomaly, reduces corruption and updates the display. Another anomaly can appear later, so a stable message is a description of that moment, not a guarantee that the run is safe.</p></section>
<section className="mt-10 space-y-4 leading-8 text-slate-300"><h2 className="text-2xl font-bold text-white">A simple way to practice</h2><ol className="list-decimal space-y-2 pl-6"><li>Open the official game and select each camera once to learn its label.</li><li>Look at the image on each feed. If the warning persists, continue looking for the visible anomaly.</li><li>Leave the affected feed selected, then press PURGE SIGNAL.</li><li>Check that the visible anomaly disappears and the status changes, then resume inspecting feeds.</li></ol><p>Checking cameras in a consistent order can help you remember what you have inspected. That is a suggested memory aid, not a tested optimal route. This guide does not establish a best interval between checks, a guaranteed survival time or a special priority for the Generator Bay.</p><p>The optional checklist below only records your own marks. It is separate from the game and will not update as the game changes. Use it while learning the labels if helpful; do not treat a checked box as live information about a feed.</p></section>
<MonitorPlanner/>
<section className="mt-10 space-y-4 leading-8 text-slate-300"><h2 className="text-2xl font-bold text-white">Build and observation limits</h2><p>This check covered switching all four feeds, a naturally appearing anomaly, the warning after switching away, and a successful purge after returning. It was performed by an automated browser agent. It was not a long survival session or a test of every possible browser and device.</p><p>The developer may replace the browser build. If the controls or warning behavior differ, follow what the current game displays and send the build details with your correction.</p><Link className="text-green-200 underline" href="/updates/">Read the source and observation log</Link><p><a className="btn-primary" href="https://carldupuy.itch.io/shift-monitor-1998">Open the official game</a></p></section></article>}
