import type {Metadata} from 'next';
import Link from 'next/link';
import Image from 'next/image';
import {buildVideoGameSchema,buildWebsiteSchema} from '@/lib/seo';
export const metadata:Metadata={title:{absolute:'SHIFT_MONITOR: 1998 — Camera Controls & Purge Guide'},description:'Start Carl Dev’s browser game and learn why an anomaly warning may stay on screen after switching cameras.',alternates:{canonical:'/'}};
export default function Home(){return <>
{[buildVideoGameSchema(),buildWebsiteSchema()].map((s,i)=><script key={i} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(s)}}/>)}
<section className="hero-bg border-b border-green-300/20"><div className="page-shell grid items-center gap-8 py-14 lg:grid-cols-2"><div><p className="mb-4 font-mono text-sm text-green-200">CARL DEV · HTML5 BROWSER GAME</p><h1 className="font-mono text-4xl font-black leading-tight sm:text-5xl">SHIFT_MONITOR: 1998</h1><p className="mt-5 text-lg leading-8 text-slate-300">Four CCTV feeds. A corruption meter. One purge button. Find the camera showing the anomaly before you try to clear it.</p><div className="mt-7 flex flex-wrap gap-3"><a className="btn-primary" href="https://carldupuy.itch.io/shift-monitor-1998">Play on itch.io</a><Link className="btn-secondary" href="/guide/">Controls & purge guide</Link></div></div><figure><Image src="/images/observed-anomaly.png" width="1280" height="850" className="h-auto w-full rounded border border-green-300/25" alt="Observed red anomaly in CAM 02 Storage Room with the warning text and purge button visible"/><figcaption className="mt-3 text-xs leading-6 text-slate-400">Browser observation of the developer’s game, 8 October 2026. Game visuals belong to Carl Dev.</figcaption></figure></div></section>
<section className="page-shell grid gap-6 py-10 md:grid-cols-2"><div className="surface p-6"><h2 className="text-xl font-bold">Warning text can be misleading</h2><p className="mt-3 leading-7 text-slate-300">In the browser build checked for this guide, the warning remained after switching away from the affected camera. The image, not that text alone, tells you which feed needs attention.</p><Link href="/guide/#warning" className="mt-4 inline-block text-green-200 underline">See the observed example</Link></div><div className="surface p-6"><h2 className="text-xl font-bold">What this guide covers</h2><p className="mt-3 leading-7 text-slate-300">Camera labels, switching, selecting the right feed and the result of a successful purge. The guide records a particular browser build; it does not promise a winning rotation or a survival score.</p><Link href="/updates/" className="mt-4 inline-block text-green-200 underline">Sources and test scope</Link></div></section></>}
