import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
const put=(file,text)=>fs.writeFileSync(path.join(root,file),text.trim()+'\n');
const config=JSON.parse(fs.readFileSync(path.join(root,'src/data/site.config.json')));
delete config.game.published; delete config.game.lastChecked; delete config.game.itchTagUrl;
config.seo.siteTitle='SHIFT_MONITOR: 1998 — Camera Controls & Purge Guide';
config.seo.siteDescription='A guide to the four cameras, the persistent warning message and the purge button in Carl Dev’s browser game, with an observed example.';
config.routes=config.routes.filter(r=>['/','/guide'].includes(r.path));
config.sources=[{name:'Official game page',url:config.game.officialUrl}];
put('src/data/site.config.json',JSON.stringify(config,null,2));
put('vercel.json',JSON.stringify({buildCommand:'npm run build'},null,2));
put('src/data/gameplay.json',JSON.stringify({cameras:[
 {name:'CAM 01 — Main Hallway',role:'Camera feed',checkRule:'Select CAM 01 to view the hallway.'},
 {name:'CAM 02 — Storage Room',role:'Camera feed',checkRule:'Select CAM 02 to view storage.'},
 {name:'CAM 03 — Security Office',role:'Camera feed',checkRule:'Select CAM 03 to view the office.'},
 {name:'CAM 04 — Generator Bay',role:'Camera feed',checkRule:'Select CAM 04 to view the generator bay.'}
],features:[{title:'Find the visible anomaly',body:'The warning can remain on screen after changing feeds. Check the image before pressing PURGE SIGNAL.'},{title:'Clear the affected feed',body:'Select the camera showing the anomaly, then use PURGE SIGNAL.'}]},null,2));
put('src/components/Footer.tsx',`import Link from 'next/link';
export default function Footer(){return <footer className="page-shell mt-12 border-t border-green-300/20 py-8 text-sm leading-7 text-slate-400"><p>Unofficial companion to Carl Dev’s HTML5 game. Site owner: Hlele. AI-assisted writing and browser checks; no claim of personal playtesting by the owner.</p><nav className="mt-3 flex flex-wrap gap-5"><Link href="/guide/">Controls & purge guide</Link><Link href="/updates/">Sources & observations</Link><Link href="/about/">About</Link><Link href="/privacy-policy/">Privacy</Link><Link href="/terms/">Terms</Link><a href="mailto:lianlele168@gmail.com">Contact</a></nav></footer>}`);
let header=fs.readFileSync(path.join(root,'src/components/Header.tsx'),'utf8');
header=header.replace(/const navItems = \[[\s\S]*?\];/,`const navItems = [{href:"/play/",label:"Play",icon:Play},{href:"/guide/",label:"Controls & purge",icon:FileText},{href:"/updates/",label:"Sources",icon:Monitor}];`);
header=header.replace(/const staticSearchItems = \[[\s\S]*?\];/,`const staticSearchItems = [{title:"Play the official game",detail:"Carl Dev’s itch.io page",href:"/play/",type:"Play"},{title:"Camera controls and persistent warning",detail:"Find the visible anomaly before using purge",href:"/guide/",type:"Guide"},{title:"Sources and browser observations",detail:"What was checked on 8 October 2026",href:"/updates/",type:"Sources"}];`);
header=header.replaceAll('href: "/camera-guide"','href: "/guide/"').replace('Cycle timing, purge windows, and corruption pressure','Camera controls and warning behavior');
put('src/components/Header.tsx',header);
let seo=fs.readFileSync(path.join(root,'src/lib/seo.ts'),'utf8');
seo=seo.replace('publisher: {','author: {').replace(/    potentialAction: \{[\s\S]*?    \},\n/,'');
put('src/lib/seo.ts',seo);
put('src/components/MonitorPlanner.tsx',`"use client";
import {useState} from 'react';
const feeds=['Main Hallway','Storage Room','Security Office','Generator Bay'];
export default function MonitorPlanner(){
 const [checked,setChecked]=useState<string[]>([]);
 return <section className="surface mt-8 p-6" aria-labelledby="checklist-title"><h2 id="checklist-title" className="text-xl font-bold">Optional camera checklist</h2><p className="mt-3 text-sm leading-7 text-slate-300">Mark feeds you have looked at, then reset for another pass. This is a manual memory aid. It cannot read the game, detect an anomaly or tell you that a camera is safe. Marks disappear on refresh.</p><div className="my-5 grid gap-3 sm:grid-cols-2">{feeds.map(feed=><label key={feed} className="flex cursor-pointer items-center gap-3 rounded border border-green-300/25 p-3"><input type="checkbox" checked={checked.includes(feed)} onChange={()=>setChecked(prev=>prev.includes(feed)?prev.filter(x=>x!==feed):[...prev,feed])}/>{feed}</label>)}</div><p role="status" className="mb-4 text-sm text-green-200">{checked.length ? checked.length+' of 4 marked' : 'No feeds marked yet.'}</p><button className="btn-secondary" onClick={()=>setChecked([])} disabled={!checked.length}>Reset checklist</button></section>;
}`);
put('src/app/page.tsx',`import type {Metadata} from 'next';
import Link from 'next/link';
import {buildVideoGameSchema,buildWebsiteSchema} from '@/lib/seo';
export const metadata:Metadata={title:{absolute:'SHIFT_MONITOR: 1998 — Camera Controls & Purge Guide'},description:'Start Carl Dev’s browser game and learn why an anomaly warning may stay on screen after switching cameras.',alternates:{canonical:'/'}};
export default function Home(){return <>
{[buildVideoGameSchema(),buildWebsiteSchema()].map((s,i)=><script key={i} type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(s)}}/>)}
<section className="hero-bg border-b border-green-300/20"><div className="page-shell grid items-center gap-8 py-14 lg:grid-cols-2"><div><p className="mb-4 font-mono text-sm text-green-200">CARL DEV · HTML5 BROWSER GAME</p><h1 className="font-mono text-4xl font-black leading-tight sm:text-5xl">SHIFT_MONITOR: 1998</h1><p className="mt-5 text-lg leading-8 text-slate-300">Four CCTV feeds. A corruption meter. One purge button. Find the camera showing the anomaly before you try to clear it.</p><div className="mt-7 flex flex-wrap gap-3"><a className="btn-primary" href="https://carldupuy.itch.io/shift-monitor-1998">Play on itch.io</a><Link className="btn-secondary" href="/guide/">Controls & purge guide</Link></div></div><figure><img src="/images/observed-anomaly.png" width="1280" height="850" className="h-auto w-full rounded border border-green-300/25" alt="Observed red anomaly in CAM 02 Storage Room with the warning text and purge button visible"/><figcaption className="mt-3 text-xs leading-6 text-slate-400">Browser observation of the developer’s game, 8 October 2026. Game visuals belong to Carl Dev.</figcaption></figure></div></section>
<section className="page-shell grid gap-6 py-10 md:grid-cols-2"><div className="surface p-6"><h2 className="text-xl font-bold">Warning text can be misleading</h2><p className="mt-3 leading-7 text-slate-300">In the browser build checked for this guide, the warning remained after switching away from the affected camera. The image, not that text alone, tells you which feed needs attention.</p><Link href="/guide/#warning" className="mt-4 inline-block text-green-200 underline">See the observed example</Link></div><div className="surface p-6"><h2 className="text-xl font-bold">What this guide covers</h2><p className="mt-3 leading-7 text-slate-300">Camera labels, switching, selecting the right feed and the result of a successful purge. The guide records a particular browser build; it does not promise a winning rotation or a survival score.</p><Link href="/updates/" className="mt-4 inline-block text-green-200 underline">Sources and test scope</Link></div></section></>}
`);
put('src/app/guide/page.tsx',`import type {Metadata} from 'next';
import Link from 'next/link';
import MonitorPlanner from '@/components/MonitorPlanner';
export const metadata:Metadata={title:'Camera controls and the persistent anomaly warning',description:'An observed walkthrough of camera selection, a warning that persists on other feeds, and clearing the actual anomaly in SHIFT_MONITOR: 1998.',alternates:{canonical:'/guide/'}};
export default function Guide(){return <article className="page-shell max-w-4xl py-10"><p className="font-mono text-sm text-green-200">CONTROLS · OBSERVED BROWSER BUILD</p><h1 className="mt-4 text-3xl font-black leading-tight sm:text-5xl">Find the right camera before you purge</h1><p className="mt-5 text-lg leading-8 text-slate-300">If you switch cameras and still see “WARNING: ANOMALY DETECTED”, do not assume the new feed contains a second anomaly. In the build checked on 8 October 2026, that text can remain even when the visible entity is on another camera.</p>
<section className="mt-10 space-y-4 leading-8 text-slate-300"><h2 className="text-2xl font-bold text-white">The four camera buttons</h2><p>CAM 01 selects Main Hallway, CAM 02 selects Storage Room, CAM 03 selects Security Office, and CAM 04 selects Generator Bay. Read the label at the bottom left after switching to check which feed is active. These are the labels displayed in the running game, not four different difficulty tiers.</p><p>Use the camera buttons to examine the feeds. When you find the visible anomaly, keep that camera selected and press PURGE SIGNAL. The game’s supplied browser code checks whether the selected camera matches the anomaly’s camera. Pressing purge on another feed does not clear that anomaly.</p></section>
<section id="warning" className="mt-10 space-y-4 leading-8 text-slate-300"><h2 className="text-2xl font-bold text-white">Observed example: a warning on the wrong feed</h2><p>During an automated browser check, an anomaly appeared naturally in CAM 02, Storage Room. It was visible as a red shape, and the top-right status changed to the warning. After selecting another camera, the red shape was no longer visible, but the warning text remained.</p><figure><img src="/images/observed-anomaly.png" width="1280" height="850" className="h-auto w-full rounded border border-green-300/20" alt="Red anomaly observed in the Storage Room before a successful purge"/><figcaption className="text-xs leading-6 text-slate-400">The affected Storage Room feed during the 8 October 2026 browser check. Carl Dev’s game, captured for this guide.</figcaption></figure><p>Returning to CAM 02 and pressing PURGE SIGNAL removed the shape. The status then became “SIGNAL: STABLE”. This is a useful distinction when learning the controls: a persistent warning means you should inspect the feeds, not repeatedly purge whichever camera is currently selected.</p><p>The checked code also explains the behavior. Switching away hides the entity; it does not reset the warning while an anomaly exists elsewhere. A successful purge clears the anomaly, reduces corruption and updates the display. Another anomaly can appear later, so a stable message is a description of that moment, not a guarantee that the run is safe.</p></section>
<section className="mt-10 space-y-4 leading-8 text-slate-300"><h2 className="text-2xl font-bold text-white">A simple way to practice</h2><ol className="list-decimal space-y-2 pl-6"><li>Open the official game and select each camera once to learn its label.</li><li>Look at the image on each feed. If the warning persists, continue looking for the visible anomaly.</li><li>Leave the affected feed selected, then press PURGE SIGNAL.</li><li>Check that the visible anomaly disappears and the status changes, then resume inspecting feeds.</li></ol><p>Checking cameras in a consistent order can help you remember what you have inspected. That is a suggested memory aid, not a tested optimal route. This guide does not establish a best interval between checks, a guaranteed survival time or a special priority for the Generator Bay.</p><p>The optional checklist below only records your own marks. It is separate from the game and will not update as the game changes. Use it while learning the labels if helpful; do not treat a checked box as live information about a feed.</p></section>
<MonitorPlanner/>
<section className="mt-10 space-y-4 leading-8 text-slate-300"><h2 className="text-2xl font-bold text-white">Build and observation limits</h2><p>This check covered switching all four feeds, a naturally appearing anomaly, the warning after switching away, and a successful purge after returning. It was performed by an automated browser agent. It was not a long survival session or a test of every possible browser and device.</p><p>The developer may replace the browser build. If the controls or warning behavior differ, follow what the current game displays and send the build details with your correction.</p><Link className="text-green-200 underline" href="/updates/">Read the source and observation log</Link><p><a className="btn-primary" href="https://carldupuy.itch.io/shift-monitor-1998">Open the official game</a></p></section></article>}
`);
function simple(slug,title,body){put('src/app/'+slug+'/page.tsx',`import type {Metadata} from 'next';\nimport Link from 'next/link';\nexport const metadata:Metadata={title:${JSON.stringify(title)},alternates:{canonical:${JSON.stringify('/'+slug+'/')}},robots:{index:false,follow:true}};\nexport default function Page(){return <article className="page-shell max-w-4xl py-10"><Link className="text-green-200 underline" href="/">Home</Link><h1 className="my-6 text-3xl font-bold">${title}</h1><div className="space-y-5 text-base leading-8 text-slate-300">${body}</div></article>}`);}
simple('play','Play the official browser game',`<p>SHIFT_MONITOR: 1998 is a released HTML5 browser game by Carl Dev. Open the developer’s itch.io page to start its current version.</p><p><a className="btn-primary" href="https://carldupuy.itch.io/shift-monitor-1998">Open on itch.io</a></p><p>This companion does not host a copy of the game. If the game fails to load, check the developer’s page for current availability; refreshing may restart a session.</p><p><Link className="text-green-200 underline" href="/guide/">Read the camera and purge controls</Link></p>`);
simple('updates','Sources and browser observations',`<h2 className="text-xl font-bold">Checked on 8 October 2026</h2><p><a className="text-green-200 underline" href="https://carldupuy.itch.io/shift-monitor-1998">Carl Dev’s official itch.io page</a> identifies the game as a released HTML5 game and describes four CCTV feeds and purging corrupted frequencies.</p><p>The browser build linked by that page was <a className="break-all text-green-200 underline" href="https://html-classic.itch.zone/html/18906721/SHIFT_MONITOR%201998/index.html?v=1787394666">build 18906721</a>. Its supplied source identifies the camera labels and the selected-camera check in the purge action.</p><h2 className="text-xl font-bold">What the browser agent actually did</h2><p>The agent opened the developer’s build, selected CAM 01–04, waited for an anomaly to appear naturally, switched away, returned to the affected camera and clicked PURGE SIGNAL. The warning persisted on the other feed; a successful purge removed the entity and changed the status to SIGNAL: STABLE. No game state was injected for this observation.</p><p>The observation covers this sequence and this build. It does not verify an optimal strategy, long-run survival, mobile play or future updates. Game screenshots on this site were captured during that check; the game and its visuals belong to Carl Dev.</p><h2 className="text-xl font-bold">Content correction</h2><p>Earlier versions of this companion included an invented risk score and safe-purge-window planner. Those predictions have been removed. Separate camera, anomaly and survival pages now point to the consolidated controls guide.</p><p>Site owner: Hlele. Research, source comparison and browser observation: Codex agent. This log does not attribute playtesting or approval to the owner.</p>`);
simple('about','About this guide',`<p>This is an unofficial companion to SHIFT_MONITOR: 1998, operated by Hlele. It is not affiliated with Carl Dev or itch.io. Despite the network domain, this game is an HTML5 browser game, not a Roblox experience.</p><p>The guide was written with AI assistance. A browser agent performed the control sequence described in the <Link className="text-green-200 underline" href="/updates/">source log</Link>. We do not claim personal playtesting by the site owner.</p><p>For corrections, email <a className="text-green-200 underline" href="mailto:lianlele168@gmail.com">lianlele168@gmail.com</a> with the affected page and supporting evidence. No response time is promised.</p>`);
simple('privacy-policy','Privacy',`<p>The camera checklist stores marks only in the current page’s memory. Refreshing clears them. This site has no account form and the checklist sends no marks to a server.</p><p>Normal page requests are handled by the hosting provider, which may process technical request information. Following an itch.io link opens a separate service with its own privacy practices. Emailing the contact address shares the information in your message.</p><p>Contact: <a className="text-green-200 underline" href="mailto:lianlele168@gmail.com">lianlele168@gmail.com</a>.</p>`);
simple('terms','Terms',`<p>This unofficial guide provides information about the linked browser build. Controls and behavior may change when the developer updates the game. The checklist is a manual note aid and has no connection to the running game.</p><p>SHIFT_MONITOR: 1998 and its visuals belong to their respective creator. External game services have their own terms. Report factual or attribution concerns to <a className="text-green-200 underline" href="mailto:lianlele168@gmail.com">lianlele168@gmail.com</a>.</p>`);
for(const [slug,title] of [['camera-guide','Camera guide moved'],['anomaly-guide','Anomaly guide moved'],['survival-tips','Survival advice corrected']])simple(slug,title,`<p>The camera controls and observed warning behavior are now explained together in the guide below. Earlier unsupported camera priorities and survival predictions have been removed.</p><p><Link className="btn-primary" href="/guide/">Read the controls and purge guide</Link></p>`);
put('public/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>https://shiftmonitor1998.robloxwikihub.com/</loc></url><url><loc>https://shiftmonitor1998.robloxwikihub.com/guide/</loc></url></urlset>`);
fs.mkdirSync(path.join(root,'public/images'),{recursive:true});
fs.copyFileSync(path.join(root,'quality/artifacts/sources/game-anomaly.png'),path.join(root,'public/images/observed-anomaly.png'));
